//! Regression test: with default parameters and KR normalization, the Rust
//! Arrowhead port must reproduce juicer_tools' `arrowhead` output on the
//! 4DNFIZ1ZVXC8 fixture.
//!
//! `tests/data/4DNFIZ1ZVXC8.5kb.hic` (single 5 kb resolution, regenerated by
//! `scripts/generate_arrowhead_fixture.sh` together with the reference
//! `4DNFIZ1ZVXC8.5kb.arrowhead.bedpe`) is a lossless hictk conversion of the
//! committed mcool. The reference comes from juicer_tools 2.20.00
//! (`arrowhead -k KR -r 5000`), the release the port is aligned to.
//!
//! Both `.hic` and `.mcool` are gitignored; like the other big-fixture tests,
//! this one assumes they are present locally.
//!
//! Note on memory: the default sweep keeps several 2001×2001 window matrices
//! per chromosome and the chromosomes run on the rayon pool, so the test
//! needs a few GB of RAM in debug mode.

use cooler_rs::{arrowhead, File};

const HIC: &str = "tests/data/4DNFIZ1ZVXC8.5kb.hic";
const RES: u32 = 5_000;
const EXPECTED: &str = include_str!("data/4DNFIZ1ZVXC8.5kb.arrowhead.bedpe");

/// One bedpe row of juicer_tools' `5000_blocks.bedpe` (header lines skipped).
struct Rec {
    chrom: String,
    start: u64,
    end: u64,
    score: f64,
    up_var: f64,
    lo_var: f64,
    up_sign: f64,
    lo_sign: f64,
}

fn parse_bedpe(text: &str) -> Vec<Rec> {
    text.lines()
        .filter(|l| !l.is_empty() && !l.starts_with('#'))
        .map(|line| {
            let f: Vec<&str> = line.split_whitespace().collect();
            // chr1 x1 x2 chr2 y1 y2 name score strand1 strand2 color
            // score uVar lVar upSign loSign
            assert_eq!(f[0], f[3], "bedpe row is not intrachromosomal");
            assert_eq!(f[1], f[4], "bedpe x1 != y1");
            assert_eq!(f[2], f[5], "bedpe x2 != y2");
            Rec {
                chrom: f[0].to_string(),
                start: f[1].parse().expect("bad bedpe start"),
                end: f[2].parse().expect("bad bedpe end"),
                score: f[7].parse().expect("bad bedpe score"),
                up_var: f[12].parse().expect("bad bedpe uVar"),
                lo_var: f[13].parse().expect("bad bedpe lVar"),
                up_sign: f[14].parse().expect("bad bedpe upSign"),
                lo_sign: f[15].parse().expect("bad bedpe loSign"),
            }
        })
        .collect()
}

#[test]
fn default_params_reproduce_juicer_arrowhead() {
    let f = File::open(HIC, RES)
        .expect("open 5kb hic (regenerate with scripts/generate_arrowhead_fixture.sh)");
    let domains = arrowhead::call_domains(&f, Some("KR"), &arrowhead::Params::default(), None)
        .expect("call_domains");

    let mut expected = parse_bedpe(EXPECTED);
    assert_eq!(domains.len(), expected.len(), "domain count differs");

    // Both sides sort per chromosome by (start, end); juicer exports each
    // chromosome's features in the order they were accumulated.
    let mut domains = domains;
    domains.sort_by(|a, b| a.chrom.cmp(&b.chrom).then(a.start.cmp(&b.start)));
    expected.sort_by(|a, b| a.chrom.cmp(&b.chrom).then(a.start.cmp(&b.start)));

    for (i, (d, e)) in domains.iter().zip(&expected).enumerate() {
        assert_eq!(d.chrom, e.chrom, "domain {i} chrom differs");
        assert_eq!(d.start, e.start, "domain {i} start differs");
        assert_eq!(d.end, e.end, "domain {i} end differs");
        // juicer prints doubles via String.valueOf (shortest round-trip
        // repr), so these should agree to the last ulp or two.
        for (name, got, want) in [
            ("score", d.score, e.score),
            ("up_var", d.up_var, e.up_var),
            ("lo_var", d.lo_var, e.lo_var),
            ("up_sign", d.up_sign, e.up_sign),
            ("lo_sign", d.lo_sign, e.lo_sign),
        ] {
            assert!(
                (got - want).abs() <= 1e-12,
                "domain {i} ({}) {} differs: {got} vs {want}",
                d.chrom,
                name
            );
        }
    }
}
