//! Tests for the `cooler.balance` port.
//!
//! Coverage:
//! - an exact, hand-computed expected case (independent anchor),
//! - the balancing invariant (balanced marginals all equal),
//! - dropped bins (min_nnz / min_count / MAD-max) come back as NaN,
//! - cis-only and trans-only modes,
//! - optional identity check against fixtures generated by Python cooler.
//!
//! # Expected fixture (`tests/data/syn.balance.cooler-python.json`)
//!
//! `matches_python_cooler_fixtures` compares the Rust `balance_cooler` output
//! weight-for-weight against cooler-python on a small synthetic matrix under
//! several parameter combinations. The fixture stores one shared input matrix
//! (`matrix`) and one expected-output record per parameter combination
//! (`cases`), so the matrix lives once instead of once per case. The test is
//! skipped (with a note) when the file is absent, so no other test depends on
//! it.
//!
//! ## Regenerating
//!
//! Requires a Python venv with `cooler` and `numpy`. Run the block below from
//! `tests/data/`; it writes `syn.balance.cooler-python.json`. The fixture pins
//! `cooler_version` so a cooler bump can be audited against a freshly
//! generated fixture.
//!
//! ```python
//! import json, os, tempfile
//! import numpy as np
//! import pandas as pd
//! import cooler
//! from cooler.create import create
//!
//! OUT = "syn.balance.cooler-python.json"
//! chroms = [("chr1", 2_000_000), ("chr2", 1_000_000)]
//!
//! # Deterministic 30-bin, 2-chromosome matrix — must match the generator in
//! # `genomewide_marginals_converge` below (xorshift64, fixed seed).
//! state = 0x1234_5678_9ABC_DEF0
//! def rng():
//!     nonlocal state
//!     state ^= (state << 13) & 0xFFFF_FFFF_FFFF_FFFF
//!     state ^= state >> 7
//!     state ^= (state << 17) & 0xFFFF_FFFF_FFFF_FFFF
//!     return state
//! pixels = []
//! for lo, hi in [(0, 20), (20, 30)]:
//!     for i in range(lo, hi):
//!         for j in range(i, hi):
//!             d = j - i
//!             v = np.exp(-d / 3.0) * (0.5 + (rng() % 100) / 100.0)
//!             pixels.append((i, j, float(v)))
//! for i in range(20):
//!     for j in range(20, 30):
//!         v = 0.1 + (rng() % 50) / 500.0
//!         pixels.append((i, j, float(v)))
//!
//! cases = [
//!     ("genomewide_defaults", dict()),
//!     ("genomewide_strict", dict(min_nnz=20, min_count=5, mad_max=2)),
//!     ("genomewide_diag4", dict(ignore_diags=4)),
//!     ("genomewide_norescale", dict(rescale_marginals=False)),
//!     ("cis_only", dict(cis_only=True)),
//!     ("trans_only", dict(trans_only=True)),
//!     ("blacklist", dict(blacklist=[0, 1, 10, 20, 21, 29])),
//!     ("all_filters", dict(cis_only=True, min_nnz=20, min_count=5, mad_max=2, ignore_diags=4)),
//! ]
//!
//! def num(v):
//!     """np scalar -> float (None for NaN); array -> list."""
//!     if np.ndim(v) == 0:
//!         return None if np.isnan(v) else float(v)
//!     return [None if np.isnan(x) else float(x) for x in np.asarray(v).ravel()]
//!
//! # Fixed-size 100 kb bins tiling each chromosome, as CoolerWriter uses.
//! bin_size = 100_000
//! rows = []
//! for cid, (name, length) in enumerate(chroms):
//!     start = 0
//!     while start < length:
//!         rows.append((cid, name, start, min(start + bin_size, length)))
//!         start += bin_size
//! bins = pd.DataFrame(rows, columns=["chrom_id", "chrom", "start", "end"])
//! px = pd.DataFrame(pixels, columns=["bin1_id", "bin2_id", "count"])
//!
//! doc = {"cooler_version": cooler.__version__,
//!        "matrix": {"chroms": [{"name": c, "length": n} for c, n in chroms],
//!                   "pixels": [[int(a), int(b), float(c)] for a, b, c in sorted(pixels)]},
//!        "cases": []}
//! with tempfile.TemporaryDirectory() as tmp:
//!     path = os.path.join(tmp, "syn.cool")
//!     # cooler's default count dtype is integer; fractional counts need float64.
//!     create(path, bins, px, symmetric_upper=True, assembly="test",
//!            dtypes={"count": "float64"})
//!     clr = cooler.Cooler(path)
//!     for name, kw in cases:
//!         bias, stats = cooler.balance_cooler(clr, chunksize=1_000_000, max_iters=1000, **kw)
//!         doc["cases"].append({
//!             "name": name, "bias": [None if np.isnan(v) else float(v) for v in bias],
//!             "scale": num(stats["scale"]), "converged": bool(np.all(stats["converged"])),
//!             "cis_only": bool(stats["cis_only"]), "trans_only": bool(kw.get("trans_only", False)),
//!             "ignore_diags": stats["ignore_diags"], "mad_max": stats["mad_max"],
//!             "min_nnz": stats["min_nnz"], "min_count": stats["min_count"],
//!             "blacklist": list(kw.get("blacklist", [])),
//!             "rescale": kw.get("rescale_marginals", True),
//!             "tol": stats["tol"], "max_iters": 1000,
//!         })
//!
//! with open(OUT, "w") as f:
//!     json.dump(doc, f, indent=1)
//! ```

use std::path::Path;

use cooler_rs::{balance_cooler, BalanceParams, Chrom, Cooler, CoolerWriter, Pixel};

/// Typed view of `tests/data/syn.balance.cooler-python.json` (see the
/// "Expected fixture" section in the module docs for how it is generated): the
/// shared input matrix plus per-case expected weights and the parameters used.
#[derive(serde::Deserialize)]
struct ExpectedFixture {
    #[allow(dead_code)]
    cooler_version: String,
    matrix: ExpectedMatrix,
    cases: Vec<ExpectedCase>,
}

#[derive(serde::Deserialize)]
struct ExpectedMatrix {
    chroms: Vec<ExpectedChrom>,
    pixels: Vec<(i64, i64, f64)>,
}

#[derive(serde::Deserialize)]
struct ExpectedChrom {
    name: String,
    length: i64,
}

#[derive(serde::Deserialize)]
struct ExpectedCase {
    name: String,
    bias: Vec<Option<f64>>,
    /// Scalar for genome-wide/trans-only runs, per-chromosome array for
    /// cis-only.
    scale: ExpectedScale,
    converged: bool,
    cis_only: bool,
    trans_only: bool,
    ignore_diags: usize,
    mad_max: usize,
    min_nnz: usize,
    min_count: usize,
    blacklist: Vec<usize>,
    rescale: bool,
    tol: f64,
    max_iters: usize,
}

#[derive(serde::Deserialize)]
#[serde(untagged)]
enum ExpectedScale {
    Scalar(f64),
    // Only deserialized (cis-only cases); never read by the assertions.
    #[allow(dead_code)]
    Array(Vec<Option<f64>>),
}

fn write_cool(dir: &Path, name: &str, chroms: &[Chrom], pixels: &[Pixel]) -> Cooler {
    let path = dir.join(name);
    let writer = CoolerWriter::create(&path, chroms, 100_000).unwrap();
    writer.write_pixels(pixels).unwrap();
    Cooler::open(path).unwrap()
}

/// A single-chromosome 3×3 matrix with equal row sums: `[[0,1,1],[1,0,1],[1,1,0]]`.
/// Every nonzero marginal is 2, so it converges in one iteration to bias =
/// ones; with `rescale_marginals` the weights are `1/√2` and balanced
/// marginals sum to 1.0.
#[test]
fn expected_3x3_equal_rowsums() {
    let dir = tempfile::tempdir().unwrap();
    let cool = write_cool(
        dir.path(),
        "expected.cool",
        &[Chrom {
            name: "chr1".into(),
            length: 300_000,
        }],
        &[
            Pixel {
                bin1_id: 0,
                bin2_id: 1,
                count: 1.0,
            },
            Pixel {
                bin1_id: 0,
                bin2_id: 2,
                count: 1.0,
            },
            Pixel {
                bin1_id: 1,
                bin2_id: 2,
                count: 1.0,
            },
        ],
    );
    let p = BalanceParams {
        min_nnz: 0,
        min_count: 0,
        mad_max: 0,
        ignore_diags: 0,
        ..Default::default()
    };
    let (bias, stats) = balance_cooler(&cool, &p).unwrap();

    let inv_sqrt2 = 1.0 / 2.0f64.sqrt();
    for (i, &b) in bias.iter().enumerate() {
        assert!(
            (b - inv_sqrt2).abs() < 1e-12,
            "bin {i}: expected {inv_sqrt2}, got {b}"
        );
    }
    assert!(
        (stats.scale[0] - 2.0).abs() < 1e-12,
        "scale = {}",
        stats.scale[0]
    );
    assert!(stats.var[0] < 1e-12, "var = {}", stats.var[0]);
    assert!(stats.converged[0]);
}

/// Balancing invariant: after IC with no filters, the marginals of the
/// balanced matrix are all equal (to the mean).
#[test]
fn genomewide_marginals_converge() {
    let dir = tempfile::tempdir().unwrap();
    // chr1: 20 bins, chr2: 10 bins; cis signal with distance decay.
    let chroms = vec![
        Chrom {
            name: "chr1".into(),
            length: 2_000_000,
        },
        Chrom {
            name: "chr2".into(),
            length: 1_000_000,
        },
    ];
    let n_bins: usize = 30;
    let mut pixels = Vec::new();
    // xorshift PRNG (deterministic, no external dep).
    let mut state: u64 = 0x1234_5678_9abc_def0;
    let mut rng = move || {
        state ^= state << 13;
        state ^= state >> 7;
        state ^= state << 17;
        state
    };
    // Allocate bins to chroms (chr1: 20, chr2: 10).
    let chrom_lo = [0usize, 20, 30];
    let mut count = 0.0f64;
    for c in 0..2 {
        let (lo, hi) = (chrom_lo[c], chrom_lo[c + 1]);
        for i in lo..hi {
            for j in i..hi {
                let d = j - i;
                let v = (-(d as f64) / 3.0).exp() * (0.5 + (rng() % 100) as f64 / 100.0);
                count += v;
                pixels.push(Pixel {
                    bin1_id: i as i64,
                    bin2_id: j as i64,
                    count: v,
                });
            }
        }
    }
    // A little trans signal so genome-wide (not cis-only) is exercised.
    for i in 0..20 {
        for j in 20..n_bins {
            let v = 0.1 + (rng() % 50) as f64 / 500.0;
            count += v;
            pixels.push(Pixel {
                bin1_id: i as i64,
                bin2_id: j as i64,
                count: v,
            });
        }
    }
    let _ = count;
    let cool = write_cool(dir.path(), "syn.cool", &chroms, &pixels);

    // ignore_diags=0 so the invariant check below covers every pixel.
    let p = BalanceParams {
        min_nnz: 0,
        min_count: 0,
        mad_max: 0,
        ignore_diags: 0,
        ..Default::default()
    };
    let (bias, stats) = balance_cooler(&cool, &p).unwrap();
    assert!(
        stats.converged[0],
        "did not converge (var = {})",
        stats.var[0]
    );
    assert!(bias.iter().all(|b| !b.is_nan()));

    // Recompute marginals of the balanced matrix.
    let mut marg = vec![0.0; n_bins];
    for px in cool.pixels().unwrap() {
        let (b1, b2) = (px.bin1_id as usize, px.bin2_id as usize);
        let v = px.count * bias[b1] * bias[b2];
        marg[b1] += v;
        marg[b2] += v;
    }
    let nz: Vec<f64> = marg.into_iter().filter(|m| *m != 0.0).collect();
    let mean = nz.iter().sum::<f64>() / nz.len() as f64;
    for (i, &m) in nz.iter().enumerate() {
        assert!(
            (m - mean).abs() < 1e-3 * mean,
            "marginal {i}: {m} vs mean {mean}"
        );
    }
}

/// Bins dropped by min_nnz are NaN; the rest are finite.
#[test]
fn dropped_bins_are_nan() {
    let dir = tempfile::tempdir().unwrap();
    // Bin 2 has no pixels touching it → zero nonzeros → dropped.
    let cool = write_cool(
        dir.path(),
        "drop.cool",
        &[Chrom {
            name: "chr1".into(),
            length: 300_000,
        }],
        &[Pixel {
            bin1_id: 0,
            bin2_id: 1,
            count: 5.0,
        }],
    );
    let p = BalanceParams {
        min_nnz: 1,
        min_count: 0,
        mad_max: 0,
        ignore_diags: 0,
        ..Default::default()
    };
    let (bias, _) = balance_cooler(&cool, &p).unwrap();
    assert!(
        bias[0].is_finite(),
        "bin 0 should be finite, got {}",
        bias[0]
    );
    assert!(
        bias[1].is_finite(),
        "bin 1 should be finite, got {}",
        bias[1]
    );
    assert!(bias[2].is_nan(), "bin 2 should be dropped, got {}", bias[2]);
}

/// cis-only balances each chromosome independently: drop one chromosome's
/// data entirely and its bins go NaN while the other chromosome still
/// balances.
#[test]
fn cis_only_is_per_chromosome() {
    let dir = tempfile::tempdir().unwrap();
    // chr2 has too few nonzeros to survive min_nnz=2 → its bins go NaN
    // while chr1 still balances.
    let cool = write_cool(
        dir.path(),
        "cis.cool",
        &[
            Chrom {
                name: "chr1".into(),
                length: 300_000,
            },
            Chrom {
                name: "chr2".into(),
                length: 300_000,
            },
        ],
        &[
            Pixel {
                bin1_id: 0,
                bin2_id: 1,
                count: 1.0,
            },
            Pixel {
                bin1_id: 0,
                bin2_id: 2,
                count: 1.0,
            },
            Pixel {
                bin1_id: 1,
                bin2_id: 2,
                count: 1.0,
            }, // chr1: complete triangle
            Pixel {
                bin1_id: 3,
                bin2_id: 4,
                count: 1.0,
            }, // chr2, bins 3..5
        ],
    );
    let p = BalanceParams {
        cis_only: true,
        min_nnz: 2,
        min_count: 0,
        mad_max: 0,
        ignore_diags: 0,
        ..Default::default()
    };
    let (bias, stats) = balance_cooler(&cool, &p).unwrap();
    // chr1 converged; all three bins have exactly 2 nonzeros so none drop.
    assert!(stats.converged[0], "chr1 should converge");
    assert!(bias[0..3].iter().all(|b| b.is_finite()));
    // chr2: bins have 0 or 1 nonzero < min_nnz=2 → all dropped to NaN.
    assert!(bias[3..6].iter().all(|b| b.is_nan()));
}

/// trans-only balances against inter-chromosomal data only.
#[test]
fn trans_only_smoke() {
    let dir = tempfile::tempdir().unwrap();
    // Two chroms: mostly cis, a little trans.
    let chroms = vec![
        Chrom {
            name: "chr1".into(),
            length: 400_000,
        },
        Chrom {
            name: "chr2".into(),
            length: 400_000,
        },
    ];
    let mut pixels = vec![
        Pixel {
            bin1_id: 0,
            bin2_id: 1,
            count: 10.0,
        },
        Pixel {
            bin1_id: 1,
            bin2_id: 2,
            count: 10.0,
        },
        Pixel {
            bin1_id: 2,
            bin2_id: 3,
            count: 10.0,
        },
        Pixel {
            bin1_id: 4,
            bin2_id: 5,
            count: 10.0,
        },
        Pixel {
            bin1_id: 5,
            bin2_id: 6,
            count: 10.0,
        },
        Pixel {
            bin1_id: 6,
            bin2_id: 7,
            count: 10.0,
        },
    ];
    // trans: every chr1 bin pairs with every chr2 bin.
    for i in 0..4 {
        for j in 4..8 {
            pixels.push(Pixel {
                bin1_id: i,
                bin2_id: j,
                count: 1.0,
            });
        }
    }
    let cool = write_cool(dir.path(), "trans.cool", &chroms, &pixels);
    let p = BalanceParams {
        trans_only: true,
        min_nnz: 0,
        min_count: 0,
        mad_max: 0,
        ignore_diags: 0,
        ..Default::default()
    };
    let (bias, stats) = balance_cooler(&cool, &p).unwrap();
    assert!(
        stats.converged[0],
        "trans-only should converge (var = {})",
        stats.var[0]
    );
    assert!(bias.iter().all(|b| !b.is_nan()));
}

/// Identity check against expected fixtures generated by Python cooler.
/// Skipped (with a note) when the fixture is absent.
#[test]
fn matches_python_cooler_fixtures() {
    let fixture =
        Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/data/syn.balance.cooler-python.json");
    if !fixture.exists() {
        eprintln!(
            "skipping identity test: {} not present (regenerate it with the recipe in \
             this file's module docs)",
            fixture.display()
        );
        return;
    }
    let text = std::fs::read_to_string(&fixture).unwrap();
    let doc: ExpectedFixture = serde_json::from_str(&text).unwrap();

    // The fixture stores the shared input matrix once, then per-case
    // expected weights. Rebuild the matrix and run every case against it.
    let chroms: Vec<Chrom> = doc
        .matrix
        .chroms
        .iter()
        .map(|c| Chrom {
            name: c.name.clone(),
            length: c.length as i32,
        })
        .collect();
    let pixels: Vec<Pixel> = doc
        .matrix
        .pixels
        .iter()
        .map(|&(bin1_id, bin2_id, count)| Pixel {
            bin1_id,
            bin2_id,
            count,
        })
        .collect();
    let dir = tempfile::tempdir().unwrap();
    let cool = write_cool(dir.path(), "case.cool", &chroms, &pixels);

    for case in &doc.cases {
        let params = BalanceParams {
            cis_only: case.cis_only,
            trans_only: case.trans_only,
            ignore_diags: case.ignore_diags,
            mad_max: case.mad_max,
            min_nnz: case.min_nnz,
            min_count: case.min_count,
            blacklist: case.blacklist.clone(),
            rescale_marginals: case.rescale,
            tol: case.tol,
            max_iters: case.max_iters,
            ..Default::default()
        };
        let (bias, stats) = balance_cooler(&cool, &params).unwrap();

        assert_eq!(
            bias.len(),
            case.bias.len(),
            "case {}: bias length mismatch",
            case.name
        );
        for (i, (&got, exp)) in bias.iter().zip(&case.bias).enumerate() {
            match exp {
                None => assert!(
                    got.is_nan(),
                    "case {}: bin {i} should be NaN, got {got}",
                    case.name
                ),
                Some(e) => {
                    assert!(
                        (got - e).abs() <= 1e-9 * e.abs().max(1.0),
                        "case {}: bin {i}: got {got}, expected {e}",
                        case.name
                    );
                }
            }
        }
        assert_eq!(
            stats.converged.iter().all(|&c| c),
            case.converged,
            "case {}: converged mismatch",
            case.name
        );
        if let ExpectedScale::Scalar(expected) = case.scale {
            assert!(
                (stats.scale[0] - expected).abs() < 1e-9 * expected.abs().max(1.0),
                "case {}: scale {} vs {}",
                case.name,
                stats.scale[0],
                expected
            );
        }
    }
}
