//! Tests for the Raichu normalization port.
//!
//! Coverage:
//! - the full pipeline produces finite weights and is deterministic (fixed seed),
//! - optional identity check of the deterministic stages (`expected_contacts`,
//!   `init_weights`, `split_windows`) against fixtures generated by Python
//!   Raichu.
//!
//! # Expected fixture (`tests/data/syn.raichu.json`)
//!
//! `matches_python_raichu_fixture` compares the Rust deterministic stages
//! against Raichu's `raichu/util.py` on a fixed synthetic matrix. The fixture
//! stores `ed`, `maxd`, `ini_weights`, `valid_cols`, and `windows` for one
//! chromosome. The test is skipped (with a note) when the file is absent.
//!
//! ## Regenerating
//!
//! Requires a Python env with `numpy`. The matrix is the same deterministic
//! formula used by `synth_pixels` below (single chromosome, 40 bins).
//!
//! ```python
//! import json
//! import numpy as np
//!
//! n = 40
//! pixels = []
//! for i in range(n):
//!     for j in range(i, n):
//!         d = j - i
//!         v = np.exp(-d / 3.0) * (50.0 + ((i * 7 + j * 13) % 100))
//!         pixels.append((i, j, float(v)))
//!
//! # --- calculate_expected_core (single chrom) ---
//! marg = np.zeros(n)
//! for i, j, v in pixels:
//!     if i == j:
//!         marg[i] += v
//!     else:
//!         marg[i] += v
//!         marg[j] += v
//! valid_cols0 = marg > 0
//! max_dis = 200
//! maxd = min(n - 1, max_dis)
//! diag_sums = [0.0] * (max_dis + 1)
//! pixel_nums = [0.0] * (max_dis + 1)
//! for i, j, v in pixels:
//!     d = j - i
//!     if d <= maxd and valid_cols0[i] and valid_cols0[j]:
//!         diag_sums[d] += v
//! for d in range(maxd + 1):
//!     for i in range(n - d):
//!         if valid_cols0[i] and valid_cols0[i + d]:
//!             pixel_nums[d] += 1.0
//! ed = [float('nan')] * (max_dis + 1)
//! for i in range(max_dis + 1):
//!     for w in range(11):  # dynamic_window_size=10
//!         lo = max(i - w, 0)
//!         hi = min(i + w + 1, max_dis + 1)
//!         n_count = sum(diag_sums[lo:hi])
//!         n_pixel = sum(pixel_nums[lo:hi])
//!         if n_count > 400.0:
//!             ed[i] = n_count / n_pixel
//!             break
//! maxd_out = max(i for i in range(max_dis + 1) if not np.isnan(ed[i]))
//!
//! # --- initialize_weights ---
//! m = marg.copy()
//! log_pos = np.log(m[m > 0])
//! med = np.median(log_pos)
//! dev = np.median(np.abs(log_pos - med))
//! cutoff = np.exp(med - 5 * dev)
//! m[m < cutoff] = 0.0
//! scale = m[m > 0].mean()
//! weights = np.sqrt(m / scale)
//! valid = (weights > 0).tolist()
//!
//! # --- split_chromosome (chrom length 40 * 100000 bp, bin 100000, window 200) ---
//! ws_bp = 200 * 100000
//! chromsize = n * 100000
//! step = ws_bp // 10 * 9
//! windows = []
//! for s in range(0, chromsize, step):
//!     if chromsize - s > ws_bp // 2 * 3:
//!         e = s + ws_bp
//!         windows.append([s // 100000, e // 100000])
//!     else:
//!         windows.append([s // 100000, chromsize // 100000])
//!         break
//!
//! def num(v):
//!     return None if (isinstance(v, float) and np.isnan(v)) else float(v)
//!
//! json.dump({
//!     "ed": [num(x) for x in ed],
//!     "maxd": maxd_out,
//!     "ini_weights": [num(x) for x in weights],
//!     "valid_cols": valid,
//!     "windows": windows,
//! }, open("syn.raichu.json", "w"), indent=1)
//! ```

use std::collections::HashMap;
use std::path::Path;

use cooler_rs::{raichu_normalize, Chrom, Cooler, CoolerWriter, Pixel, RaichuParams};

/// The shared synthetic matrix: one chromosome, 40 bins, deterministic counts.
fn synth_pixels(offset: i64, n: i64) -> Vec<Pixel> {
    let mut px = Vec::new();
    for i in 0..n {
        for j in i..n {
            let d = (j - i) as f64;
            // Counts in the tens-to-hundreds so the `N=400` dynamic-window
            // threshold in `calculate_expected` is crossed.
            let v = (-d / 3.0).exp() * (50.0 + ((i * 7 + j * 13) % 100) as f64);
            px.push(Pixel {
                bin1_id: offset + i,
                bin2_id: offset + j,
                count: v,
            });
        }
    }
    px
}

fn write_cool(dir: &Path, name: &str, chroms: &[Chrom], pixels: &[Pixel]) -> Cooler {
    let path = dir.join(name);
    let writer = CoolerWriter::create(&path, chroms, 100_000).unwrap();
    writer.write_pixels(pixels).unwrap();
    Cooler::open(&path).unwrap()
}

#[test]
fn raichu_is_finite_and_deterministic() {
    let dir = tempfile::tempdir().unwrap();
    let chroms = vec![Chrom {
        name: "chr1".into(),
        length: 4_000_000,
    }];
    let clr = write_cool(dir.path(), "syn.cool", &chroms, &synth_pixels(0, 40));

    let params = RaichuParams {
        min_nnz: 5, // 40 bins, each in ~39 valid pixels; keep the threshold low
        ..RaichuParams::default()
    };

    let a = raichu_normalize(&clr, &params).unwrap();
    let b = raichu_normalize(&clr, &params).unwrap();

    assert_eq!(a.len(), 40);
    // Deterministic: identical weights across runs (fixed seed 42).
    for (x, y) in a.iter().zip(&b) {
        assert!(x == y || (x.is_nan() && y.is_nan()), "nondeterministic");
    }
    // Most bins finite (Raichu drops low-coverage bins to NaN, but not all).
    let finite = a.iter().filter(|w| w.is_finite()).count();
    assert!(finite > 30, "only {finite} finite weights");
    // Weights are strictly positive biases (Raichu writes 10^(-w) > 0).
    for w in &a {
        assert!(w.is_nan() || *w > 0.0);
    }
}

/// Identity check against expected fixtures generated by Python Raichu.
/// Skipped (with a note) when the fixture is absent.
#[test]
fn matches_python_raichu_fixture() {
    let fixture = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/data/syn.raichu.json");
    if !fixture.exists() {
        eprintln!(
            "skipping identity test: {} not present (regenerate it with the recipe in \
             tests/raichu.rs)",
            fixture.display()
        );
        return;
    }

    let text = std::fs::read_to_string(&fixture).unwrap();
    let doc: serde_json::Value = serde_json::from_str(&text).unwrap();

    // Build the same 40-bin, single-chromosome matrix.
    let n = 40usize;
    let pixels: Vec<(usize, usize, f64)> = {
        let px = synth_pixels(0, n as i64);
        px.iter()
            .map(|p| ((p.bin1_id) as usize, p.bin2_id as usize, p.count))
            .collect()
    };
    let chrom_pixels = vec![pixels.clone()];
    let chrom_n = vec![n];

    // expected_contacts (genome-wide, no included bins).
    let (ed, maxd) =
        cooler_rs::raichu::expected_contacts(&chrom_pixels, &chrom_n, None, 200, 10, 400.0);
    let exp_maxd = doc["maxd"].as_u64().unwrap() as usize;
    assert_eq!(maxd, exp_maxd);
    let exp_ed = doc["ed"].as_array().unwrap();
    for i in 0..=exp_maxd {
        let got = ed[i];
        let want = exp_ed[i].as_f64().unwrap_or(f64::NAN);
        if want.is_nan() {
            assert!(got.is_nan());
        } else {
            assert!((got - want).abs() < 1e-9 * want.abs().max(1.0));
        }
    }

    // init_weights.
    let marg = cooler_rs::raichu::marginal(n, &pixels);
    let (ini_weights, valid_cols) = cooler_rs::raichu::init_weights(&marg, None);
    let exp_w = doc["ini_weights"].as_array().unwrap();
    for i in 0..n {
        assert!((ini_weights[i] - exp_w[i].as_f64().unwrap()).abs() < 1e-9);
    }
    let exp_valid = doc["valid_cols"].as_array().unwrap();
    for i in 0..n {
        assert_eq!(valid_cols[i], exp_valid[i].as_bool().unwrap());
    }

    // split_windows.
    let windows = cooler_rs::raichu::split_windows(4_000_000, 100_000, 200 * 100_000);
    let exp_windows = doc["windows"].as_array().unwrap();
    assert_eq!(windows.len(), exp_windows.len());
    for (w, e) in windows.iter().zip(exp_windows) {
        let e = e.as_array().unwrap();
        assert_eq!(w.0, e[0].as_u64().unwrap() as usize);
        assert_eq!(w.1, e[1].as_u64().unwrap() as usize);
    }
}

/// `included_bins` / `load_bed` round-trips a BED row into local bin indices.
#[test]
fn bed_regions_map_to_local_bins() {
    // Reuse the deterministic helpers: a BED row on chr1 bp [0, 250000) at
    // 100 kb resolution maps to local bins [0, 3).
    let dir = tempfile::tempdir().unwrap();
    let bed = dir.path().join("regions.bed");
    std::fs::write(&bed, "chr1\t0\t250000\n").unwrap();

    let chroms = vec![Chrom {
        name: "chr1".into(),
        length: 4_000_000,
    }];
    let clr = write_cool(dir.path(), "syn.cool", &chroms, &synth_pixels(0, 40));

    // Build included_bins the same way the CLI does.
    let bin_size = clr.bin_size().unwrap().unwrap();
    let text = std::fs::read_to_string(&bed).unwrap();
    let mut included: HashMap<String, Vec<usize>> = HashMap::new();
    for line in text.lines() {
        let cols: Vec<&str> = line.split_whitespace().collect();
        let lo = cols[1].parse::<i64>().unwrap() / bin_size as i64;
        let hi = (cols[2].parse::<i64>().unwrap() + bin_size as i64 - 1) / bin_size as i64;
        included
            .entry(cols[0].to_string())
            .or_default()
            .extend((lo as usize)..(hi as usize));
    }
    let bins = included.get("chr1").unwrap();
    assert_eq!(bins, &vec![0, 1, 2]);

    // The pipeline still runs with a region restriction.
    let params = RaichuParams {
        min_nnz: 5,
        included_bins: Some(included),
        ..RaichuParams::default()
    };
    let bias = raichu_normalize(&clr, &params).unwrap();
    assert_eq!(bias.len(), 40);
}
